name: Gradle test CI (bogdanov-telegram-bot)
on:
  pull_request:
    branches:
      - trunk
    types:
      - opened
      - reopened
    push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0
        with:
            gradle-version: 8.7

      - name: Setting executable permissions for gradlew
        run: chmod +x ./gradlew

      - name: Test
        run: ./gradlew test --info

      - name: Build
        run: ./gradlew build -x test